In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
a = np.empty((3,4),dtype=np.uint8)
a

array([[ 32,  32,  62,  62],
       [ 62,  32,  65,  10],
       [208, 175,   7, 190]], dtype=uint8)

In [21]:
p = ([1,2,3],[4,5,6])
a = np.empty_like((p))
a

array([[-1109570720,         410,           0],
       [          0,      131074,  1616994336]])

In [25]:
p = ([1,2,3],[4,5,6])
a = np.eye(4,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [42]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])