In [1]:
import numpy as np

In [4]:
# t = 0
# for i in np.arange(10000):
#     t+=i
# t    
# این با زبان python

49995000

In [5]:
np.sum(np.arange(10000))

49995000

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.add(a,b)

array([5, 7, 9])

In [7]:
np.add.reduce(a)

6

In [8]:
np.add.accumulate(b)

array([ 4,  9, 15])

In [9]:
np.add.outer(a,b)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])